framework:
    messenger:
        # Send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration

            # Use for high priority tasks such as search jobs
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
                options:
                    queue_name: high_priority
            # Use this as a default or when you're not sure
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
                options:
                    queue_name: normal_priority
            # Use for low priority tasks such as sending emails, indexing...
            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
                options:
                    queue_name: low_priority
            # This is the default
            sync: 'sync://'
            # All failed messages end up here and can be retried
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: failed

        routing:
            # Route your messages to the transports
            'App\Message\ProcessUrlRequest': async_priority_high

        # Read more to learn why there are two buses (TL;DR: different middleware on each side - producer and consumer)
        # https://github.com/symfony/symfony/issues/32436#issuecomment-530565499

        default_bus: command.bus
        buses:
            command.bus:
                default_middleware: false
                middleware:
                    - validation
                    - add_bus_name_stamp_middleware: ['command.consumer.bus']
                    - dispatch_after_current_bus
                    - failed_message_processing_middleware
                    - send_message
                    - handle_message

            command.consumer.bus:
                middleware:
                    - doctrine_ping_connection
